### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Sparo** [jaredhanson/passport-github#15]
I get this:
`emails: [ { value: undefined } ],`
in response... so is it valid? because I need email info...

this is request:
`app.get('/auth/github', passport.authenticate('github', { scope : "user:email"}));`
and this is callback:
`app.get('/auth/github/callback', passport.authenticate('github', { failureRedirect: '/login' }), function (req, res) { res.redirect('/'); });`

**Comment by kunal-mandalia** [comment]
Thanks iliakan, I was having the same problem (email: null) I used your code to get the email address successfully.

**Comment by sunjay** [comment]
For those who see this in the future, the latest way to accomplish this is:

```javascript
  new GitHubStrategy(
    {
      clientID: ...,
      clientSecret: ...,
      callbackURL: ...,
      scope: 'user:email',
    },
    ...
  );
```
[An extra API call](https://github.com/jaredhanson/passport-github/blob/451db704e3b7e6b72266da3e1fa8f36496cd8881/lib/strategy.js#L140) will automatically be made to fetch the email.

Would be great if the documentation could be updated.

**Comment by gapsong** [comment]
@sunjay it still doesnt work for me...
Do i have to change this aswell?
`app.get('/auth/github', passportGithub.authenticate('github', {scope: ['user:email']}));`

**Comment by oliviertassinari** [comment]
I have tried `passport-github2` with no luck.
I have tried @sunjay solution and it's **working** thanks to the line he linked and https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L95 .
This issue can be closed.

**Comment by animeshsinghweb** [comment]
@gapsong @oliviertassinari It was not working, because at `passport-github2` strategy, scope should be [passed as an array](https://github.com/cfsghost/passport-github/blob/master/lib/strategy.js#L24).

**Using this for `passport-github2` strategy worked fine for me**:
If you are using `passport-github2` strategy, you just need to `scope: ['user:email']` to the options.
       passport.use(new GitHubStrategy({
            clientID: process.env.GITHUB_CLIENT_ID,
            clientSecret: process.env.GITHUB_CLIENT_SECRET,
            scope: ['user:email'],
            callbackURL: process.env.GITHUB_CALLBACK_URL
        }
which would be returning `emails` to the json file return, similar to
    emails: [ { value: 'user@xyz,com' } ]
depending upon the emails attached to their profile.

Alternatively, you can `console.log(profile)` to see the output returned.

**Comment by shoumma** [comment]
@sunjay thank you man, it really helps 👍

**Comment by sreerag-nair** [comment]
You are a life saver, @sunjay ... much thanks!

**Comment by timwheelercom** [comment]
Thank you @sunjay! Saved me a lot of headaches.

**Comment by niftylettuce** [comment]
To anyone reading this - don't waste your time - just use `passport-github2` - the core logic of this package's user profile lookup in this is written very poorly.

**Comment by itswadesh** [comment]
For me passport-github is working much better thatn passport-github2.

**Comment by niftylettuce** [comment]
@itswadesh please back up your statement with information as how it is working much better?

**Comment by itswadesh** [comment]
@niftylettuce 
- I tried to retrieve user email info. `passport-github2` retrieved only public email where as `passport-github` did both.

- Could not get typescript working with `passport-github2` (may be because of wrong typings file)

**Comment by niftylettuce** [comment]
You just need to set scopes to get that information.  This is not related to the package as far as I know.  TypeScript is completely outside the scope of the package, and not many authors I know on npm support it.  Furthermore I highly recommend you do not use it, as it is bad for open-source and it is unnecessary convolution.  Look at all the time wasted trying to get TypeScript working..

**Comment by itswadesh** [comment]
@niftylettuce I tried
`new GithubStrategy(
      {
        clientID: GITHUB_CLIENT_ID,
        clientSecret: GITHUB_CLIENT_SECRET,
        callbackURL: WWW_URL + '/auth/github/callback'
        scope: 'user:email',
      }
)`

without success

**Comment by niftylettuce** [comment]
@itswadesh see https://github.com/ladjs/passport/blob/master/index.js for working implementation.

This is used on https://forwardemail.net and https://lad.sh with success.

**Comment by thepranaygupta** [comment]
@sunjay Thanks a ton! 👍🏻
