### ISSUE TITLE
npm publish 0.1.7

### ISSUE THREAD

**Issue by pierreinglebert** [jaredhanson/passport-github#20]
The last version available on npmjs is the 0.1.5 and this repo is 0.1.7, could you please publish it ?

**Comment by lauweijie** [comment]
Any plans to publish 0.1.7 on npm?

0.1.5 lists passport-oauth 0.1.x as a dependency and that gives a deprecated warning:
`createCredentials() is deprecated, use tls.createSecureContext instead`

**Comment by ianjuma** [comment]
+1

**Comment by knownasilya** [comment]
@jaredhanson ping

**Comment by manland** [comment]
:+1:

**Comment by jaredhanson** [comment]
I've published this to npm as passport-github@1.0.0.

**Comment by burtonjc** [comment]
Thank you @jaredhanson!
