### ISSUE TITLE
Does it work with express 4?

### ISSUE THREAD

**Issue by leedorian** [jaredhanson/passport-github#22]
Does it work with express 4? Is there express 4 example?

**Comment by kevinSuttle** [comment]
The auth call works, but I'm not having any luck getting data. /accounts just redirects to /, and it defaults to only getting public info, which you don't need auth for.

**Comment by kevinSuttle** [comment]
This works: https://github.com/aselbie/passport-github/blob/a6c9d34e2c6ee442e8a0906c1e5269507bd67984/examples/login/app.js

**Comment by tadman** [comment]
I've had no problems with Express 4.x by following that example. Probably worth closing this issue to avoid worrying people.

**Comment by jaredhanson** [comment]
Examples have been moved to separate repositories. Closing.

Refer to this for a example using Express 4.0 and OAuth 2.0:
https://github.com/passport/express-4.x-facebook-example
