### ISSUE TITLE
Dealing with token removal of github oauth api

### ISSUE THREAD

**Issue by drorweiss** [jaredhanson/passport-github#36]
GitHub is now going to change the oauth app authentication mechanism - see https://developer.github.com/changes/2014-12-08-removing-authorizations-token/

How does passport going to deal with this change? Will the GitHubStrategy still provide the access token to the callback?

**Comment by zhangchiqing** [comment]
I don't think github's api change would affect oauth here.

passport-github [uses GitHub OAuth to get token](https://developer.github.com/v3/oauth/#github-redirects-back-to-your-site), see source code here: https://github.com/jaredhanson/passport-github/blob/master/lib/strategy.js#L54, which is not in the [affected API list](https://developer.github.com/v3/oauth_authorizations/#deprecation-notice).

**Comment by drorweiss** [comment]
Yes, you're probably correct
