### ISSUE TITLE
router is deprecated..

### ISSUE THREAD

**Issue by JohnMcLear** [jaredhanson/passport-github#44]
https://github.com/jaredhanson/passport-github/blob/master/examples/login/app.js#L66

```
[2015-06-22 22:13:14.958] [ERROR] console - Error: 'app.router' is deprecated!
Please see the 3.x to 4.x migration guide for details on how to update your app.
```

**Comment by simison** [comment]
Looks like just removing that line would help: http://expressjs.com/guide/migrating-4.html#routing

**Comment by JohnMcLear** [comment]
@jaredhanson did you wanna go ahead and fix your example providers?

**Comment by JohnMcLear** [comment]
```
git clone https://github.com/jaredhanson/passport-github.git
cd passport-github/examples/login/
npm install
node app.js
```

Returns
```
jose@PBOH-SNUG:~/test/passport-github/examples/login$ node app.js
/home/jose/test/passport-github/examples/login/app.js:51
var app = express.createServer();
                  ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/jose/test/passport-github/examples/login/app.js:51:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jaredhanson** [comment]
> did you wanna go ahead and fix your example providers?

Other than pinning deps to Express 2 or 3, no.  If you want to submit Express 4 examples, that'd be welcome.

**Comment by JohnMcLear** [comment]
*flips the table.

**Comment by JohnMcLear** [comment]
Do you a deal, you get it working on one of your repos(IE this one) and I will do the other providers..

**Comment by jaredhanson** [comment]
How about this deal: I am already giving away tons of free code.  Fixing old examples isn't my highest priority.  The module itself functions fine, and its pretty easy to read Express changelogs and figure out how to make it work.

**Comment by simison** [comment]
@JohnMcLear did you have a look at

https://github.com/jaredhanson/passport-github/pull/23
https://github.com/jaredhanson/passport-github/pull/31
https://github.com/jaredhanson/passport-github/pull/29

**Comment by JohnMcLear** [comment]
@jaredhanson Look at my profile...   I give away tons of free code too but I also maintain it and fix it when it's broken.  I'd like to encourage you to do the same.  Looks like this is just poor project maintenance and I'd rather not be part of it.  Best of luck.
