### ISSUE TITLE
Stateless example (or bug?)

### ISSUE THREAD

**Issue by hejhi** [jaredhanson/passport-github#49]
Do you know how we can get the token in /auth/github/callback? I'm not sure how to proceed if not...is there another example on how this would be achieved? To make the call to /login/oauth/access_token in the callback there with the code parameter is marked as expired, presumably because it was already used earlier (I'm guessing).

**Comment by jaredhanson** [comment]
I don't know what this is referring to.  This strategy handles the `/login/oauth/access_token` request internally and supplies the resulting access token to the `verify` callback.  There is no need to exchange the `code` manually.
