### ISSUE TITLE
Github Enterprise - InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by hankthewhale** [jaredhanson/passport-github#57]
This might be an enterprise specific issue perhaps?

Here is my code

**passport.js**
```js
passport.use(new GitHubStrategy({
    clientID: config.github.id,
    clientSecret: config.github.secret,
    callbackURL: 'http://127.0.0.1:3001/auth/github/callback',
    authorizationURL: 'https://github.our_domain.com/login/oauth/authorize'
  },
  function(accessToken, refreshToken, profile, cb) {
    console.log("accessToken==" + accessToken)
    User.findOrCreate({ githubId: profile.id }, function (err, user) {
      return cb(err, user);
    });
  }
));
```

**server.js**
```js
app.get('/login/github',
  passport.authenticate('github', {session: false })
);

app.get('/auth/github/callback',
  passport.authenticate('github', { failureRedirect: '/login' }),
  (req, res) => {
    res.redirect('/');
  }
);
```

When I hit `/login/github` it bounces out to Github Enterprise, I give the app permissions, it then hits the callback and lands on `http://127.0.0.1:3001/auth/github/callback?code=random_code` with the above error.

Am I missing anything else? From what I understand (and I understand very little) it should obtain the token and I should be good to start hitting the GHE API.

Thanks!

**Comment by hankthewhale** [comment]
Realized I needed to pass in two more options. `userProfileURL` and `tokenURL`

Now receiving this error:
`Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only`

**Comment by hankthewhale** [comment]
Should I assume that this repo is dead and fork our own version?

**Comment by jaredhanson** [comment]
Why would you assume that?

```
Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only
```

That error has nothing to do with this module, so forking won't help.  It is in your application code.

**Comment by hankthewhale** [comment]
@jaredhanson 
My apologies. I only assumed because I opened a few weeks ago and noticed that #45 was from last year with no response.

passport-github was part of the error trace @ https://github.com/jaredhanson/passport-github/blob/master/lib/strategy.js#L174

**Comment by binario200** [comment]
I having same issue, could because my machine is behid a corporate firewall?

`Connect
500 InternalOAuthError: Failed to obtain access token
   at Strategy.OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:370:17)
   at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /usr/src/app/node_modules/oauth/lib/oauth2.js:177:18
   at ClientRequest.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:148:5)
   at emitOne (events.js:96:13)
   at ClientRequest.emit (events.js:188:7)
   at TLSSocket.socketOnEnd (_http_client.js:342:9)
   at emitNone (events.js:91:20)
   at TLSSocket.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:926:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by rakesh113** [comment]
binario200 so how did u resolve it?

**Comment by binario200** [comment]
@rakesh113 At the begin I tried some workarrounds like setting proxy settings to the oauth request like as I documented [here](https://github.com/binario200/passport-social-auth) 

Then I realize that passport-github works very well but with the "public"  Github (maybe some hardcode github.com urls). 

I was using Github Enterprise at my job so I finally decide to use  [simple-oauth2](https://www.npmjs.com/package/simple-oauth2) to get authenticated by github enterprise and I finished with a solution like this

```
var dotenv = require('dotenv');
 dotenv.load({ path: '.env' });

 var oauth2 = require('simple-oauth2')({
     clientID: process.env.GITHUB_ID,
     clientSecret: process.env.GITHUB_SECRET,
     site: process.env.BASE_SITE,
     tokenPath: process.env.TOKEN_PATH,
     authorizationPath: process.env.AUTHORIZATION_PATH
 });

 var authorizeConfig = {
     redirect_uri: process.env.CALLBACKURL,
     scope: process.env.GITHUB_SCOPE,
     state: ''
 };

 catch_callback: function catch_callback(req, res, next) {

    var tokenConfig = {
      code: req.query.code,
      redirect_uri: process.env.CALLBACKURL
      //,expires_in: '7200'
    };

    oauth2.authCode.getToken(tokenConfig, saveToken);

    function saveToken(error, result) {
      if (error) {
        console.log('Error Saving Access Token ', error.message);
        return next(error);
      }

      //var token = oauth2.accessToken.create(result);
      var parsedAccessToken = oauthResultParser(result);
      req.session.AccessToken = parsedAccessToken;

      return next();
    }

  }
```

You can see the whole solution [here](https://gist.github.com/binario200/d983d84e583360a4b5a5b3f0870bd9ba)

**Comment by tCm3nc** [comment]
This is still broken ? GHE is not a supported feature in WikiJS for corporate environments
