### ISSUE TITLE
TypeError: Cannot read property '0' of undefined 

### ISSUE THREAD

**Issue by zxhs1988** [jaredhanson/passport-github#59]
Hi, I use the development of the account test is no problem, but the use of other non developer account landing on this issue

GET /auth/github 302 7.058 ms - 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '0' of undefined
    at /Applications/XAMPP/xamppfiles/htdocs/html/baoniu-voting-app/config/passport.js:75:62
    at Query.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/html/baoniu-voting-app/node_modules/mongoose/lib/model.js:3352:16)
    at /Applications/XAMPP/xamppfiles/htdocs/html/baoniu-voting-app/node_modules/mongoose/node_modules/kareem/index.js:244:21
    at /Applications/XAMPP/xamppfiles/htdocs/html/baoniu-voting-app/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)

**Comment by jaredhanson** [comment]
That stack trace points to your application code, not this module
