### ISSUE TITLE
"The code passed is incorrect or expired"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jaredhanson/passport-github#65]
I keep getting this error, even after revoking my user tokens and clearing cookies.

The browser URL looks like "https://mywebsite/admin/auth?code=12346"

Seems like the error is caused by something else I'm doing wrong, since I'm not actually using an old code or anything.

How do I get to the bottom of this?

**Comment by GeoffreyPlitt** [comment]
@jaredhanson Any ideas?

**Comment by imujjwal96** [comment]
@GeoffreyPlitt Got a solution?

**Comment by GeoffreyPlitt** [comment]
No, but I had something wrong with my redirects. If you follow an example perfectly you shouldn't see this.

**Comment by nikolay-govorov** [comment]
Hello. I catch the same error in my app. Here is an example:

```js
const Koa = require('koa');
const Router = require('koa-router');
const passport = require('koa-passport');
const { Strategy: GithubStrategy } = require('passport-github');

passport.use(new GithubStrategy(
  {
    clientID: 'client-id',
    clientSecret: 'client-secret-key',
    callbackURL: 'http://localhost:3000/auth/github/callback',
  },
  (accessToken, refreshToken, profile, done) => done(null, profile)
));

passport.serializeUser((user, done) => done(null, user));

passport.deserializeUser((user, done) => done(null, user));

const app = new Koa();

app.use(passport.initialize());

const router = new Router();

router.get('/', (ctx) => {
  ctx.body = 'This is root page ("/")';
});

router.get('/auth/github', passport.authenticate('github'));
router.get('/auth/github/callback', passport.authenticate('github', { successRedirect:'/', failureRedirect: '/' }));

//Middleware: authed
const authed = (ctx, next) => (ctx.isAuthenticated() ? (next()) : ctx.redirect('/auth/github'));

router.get('/app', authed, (ctx) => {
  ctx.body = 'Secured Zone';
});

app.use(router.routes());

app.listen(3000);
```

**Comment by Martii** [comment]
I somehow had a corrupt browser profile that caused this issue. Created a new one and it went away.

**Comment by hayreddintuzel** [comment]
@Martii @bdfdm25 Did you solve your problems?

**Comment by vishwa3** [comment]
I too am getting this error
`TokenError: The code passed is incorrect or expired.`

**Comment by JoshInLisbon** [comment]
I am also getting this issue. I created a new github account to try out an app created there... but no luck. I am getting with:

`client = Octokit::Client.new(
      client_id: ENV['GITHUB_CLIENT_ID'],
      client_secret: ENV['GITHUB_CLIENT_SECRET']
    )`

**Comment by JoshInLisbon** [comment]
> I somehow had a corrupt browser profile that caused this issue. Created a new one and it went away.

What does this mean? How did you fix it?

**Comment by Martii** [comment]
@JoshInLisbon 

> What does this mean?

* [Firefox](https://developer.mozilla.org/docs/Mozilla/Firefox/Multiple_profiles)
* [Chrome](https://support.google.com/chrome/answer/2364824)

> How did you fix it?

* https://www.google.com/search?q=how+to+create+a+new+chrome+browser+profile
* https://www.google.com/search?q=how+to+create+a+new+firefox+browser+profile

**Comment by wgcv** [comment]
I got this error when the callback code is expired (Go back in the navigator)
http://localhost:3000/login/github/return?code=6970codefad3fake3ce2

**Comment by Parmeshwar-QA** [comment]
I am also experiencing this same problem. Anyone can solve it. Please reply.

error=bad_verification_code&error_description=**The+code+passed+is+incorrect+or+expired.&error**_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23bad-verification-code

#Acces Token
#The_code_passed_is_incorrect or expired

**Comment by Jobians** [comment]
Solution:
Make sure your `callbackURL` in
```
passport.use(new GithubStrategy(
  {
    clientID: 'client-id',
    clientSecret: 'client-secret-key',
    callbackURL: 'http://localhost:3000/auth/github/callback',
  },
  (accessToken, refreshToken, profile, done) => done(null, profile)
));
```

Is same thing with your `Authorization callback URL` in GitHub 
![Screenshot_2024-07-31-03-43-14-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/af07e3a4-6ce2-4289-8162-c53fe720df91)

**Comment by shulmnn** [comment]
for me it was mismatch in .env file. old data was cached and i was needed to explicitly reload env file.
