### ISSUE TITLE
Revoke?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jaredhanson/passport-github#66]
Is there a way to revoke access?

**Comment by yo34** [comment]
same question.

**Comment by yo34** [comment]
Is 's seem passport projet is not maintened

**Comment by jaredhanson** [comment]
Passport provides authentication only, in the case of GitHub it does this by obtaining an access token and the user's profile information.  Any token revocation is out-of-scope, and needs to be handled by the application, by calling the relevant [GitHub API](https://developer.github.com/v3/oauth_authorizations/#revoke-an-authorization-for-an-application)

**Comment by GeoffreyPlitt** [comment]
Is https://oauth.net/2/token-revocation/ not an option?

**Comment by jaredhanson** [comment]
If GitHub supports that API, then it would be, but I don't think they do.  Either way, any token revocation would need to happen _after_ authentication, and is not a feature of Passport.

**Comment by yo34** [comment]
@ jaredhanson, yes this is what I did. But i was wondering if there is a possibility just to logout or to delete the cookie "user_session"  that is generate with github instead.
I make a test with passport-facebook, I observe the same behaviour. When I login, after logout, the session with my client and the express server is close. But If i click on the login Facebook, it's reconnect without prompting for password. I think this is a security problem.


> Passport provides authentication only, in the case of GitHub it does this by obtaining an access token and the user's profile information. Any token revocation is out-of-scope, and needs to be handled by the application, by calling the relevant [GitHub API](https://developer.github.com/v3/oauth_authorizations/#revoke-an-authorization-for-an-application)
